Repository capstone-kelompok-7/backend-disappear, pull requests merged in 2023-11, with the labels that each got.

#1 feature:login, register
  .env.example
  .gitignore
  config/config.go
  go.mod
  go.sum
  main.go
  middlewares/log.go
  module/auth/domain/request.go
  module/auth/domain/response.go
  module/auth/handler/handler.go
  module/auth/interface.go
  module/auth/repository/repository.go
  module/auth/service/service.go
  module/users/domain/models.go
  module/users/handler/handler.go
  module/users/interface.go
  module/users/repository/respository.go
  module/users/service/service.go
  routes/routes.go
  utils/database/migrate.go
  utils/database/mysql.go
  utils/jwt.go
  utils/password.go
  utils/response/response.go
  utils/validate.go
Labels: feature

#2 add: testing register, login
  go.mod
  go.sum
  module/auth/handler/handler.go
  module/auth/mocks/HandlerAuthInterface.go
  module/auth/mocks/RepositoryAuthInterface.go
  module/auth/mocks/ServiceAuthInterface.go
  module/auth/service/service.go
  module/auth/service/service_test.go
  module/users/mocks/HandlerUserInterface.go
  module/users/mocks/RepositoryUserInterface.go
  module/users/mocks/ServiceUserInterface.go
  module/users/repository/respository.go
  utils/database/migrate.go
  utils/mocks/HashInterface.go
  utils/mocks/JWTInterface.go
  utils/password.go
Labels: improvment

#3 feature:get products
  main.go
  module/product/domain/models.go
  module/product/domain/response.go
  module/product/handler/handler.go
  module/product/interface.go
  module/product/repository/repository.go
  module/product/service/service.go
  routes/routes.go
  utils/database/migrate.go
  utils/response/response.go
Labels: feature

#4 improvment: feature login, register
  module/auth/domain/request.go
  module/auth/handler/handler.go
  module/auth/service/service.go
  module/auth/service/service_test.go
  module/users/service/service.go
Labels: improvment

#7 feature:review
  module/product/domain/models.go
  module/product/domain/response.go
  module/product/handler/handler.go
  module/product/interface.go
  module/product/repository/repository.go
  module/product/service/service.go
  module/review/domain/models.go
  module/review/handler/handler.go
  module/review/interface.go
  module/review/repository/repository.go
  module/review/service/service.go
  utils/database/migrate.go
Labels: feature

#8 Feature/middleware
  main.go
  middlewares/auth.go
  module/review/interface.go
  module/users/handler/handler.go
  module/users/interface.go
  routes/routes.go
Labels: feature

#6 update feature/voucher
  module/voucher/domain/models.go
  module/voucher/domain/request.go
  module/voucher/domain/response.go
  module/voucher/handler/handler.go
  module/voucher/interface.go
  module/voucher/repository/repository.go
  module/voucher/service/service.go
  routes/routes.go
Labels: feature

#9 bugfix:load env
  config/config.go
Labels: bugfix

#10 feature: get article
  main.go
  module/article/domain/models.go
  module/article/domain/response.go
  module/article/handler/handler.go
  module/article/interface.go
  module/article/repository/repository.go
  module/article/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#11 feature : challenge
  main.go
  module/challenge/domain/models.go
  module/challenge/domain/request.go
  module/challenge/domain/response.go
  module/challenge/handler/handler.go
  module/challenge/interface.go
  module/challenge/repository/repository.go
  module/challenge/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#12 feature:verify email
  go.mod
  go.sum
  module/auth/domain/request.go
  module/auth/handler/handler.go
  module/auth/interface.go
  module/auth/mocks/HandlerAuthInterface.go
  module/auth/mocks/RepositoryAuthInterface.go
  module/auth/mocks/ServiceAuthInterface.go
  module/auth/repository/repository.go
  module/auth/service/service.go
  module/users/domain/models.go
  module/users/repository/respository.go
  routes/routes.go
  utils/database/migrate.go
  utils/email/email.go
  utils/otp/otp.go
Labels: feature

#13 feature : category
  main.go
  module/category/.DS_Store
  module/category/domain/models.go
  module/category/domain/response.go
  module/category/handler/handler.go
  module/category/interface.go
  module/category/repository/repository.go
  module/category/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#14 feature : change password
  main.go
  module/auth/mocks/HandlerAuthInterface.go
  module/auth/mocks/RepositoryAuthInterface.go
  module/auth/mocks/ServiceAuthInterface.go
  module/auth/service/service.go
  module/auth/service/service_test.go
  module/users/domain/request.go
  module/users/handler/handler.go
  module/users/interface.go
  module/users/mocks/RepositoryUserInterface.go
  module/users/repository/respository.go
  module/users/service/service.go
  routes/routes.go
  utils/jwt.go
  utils/mocks/JWTInterface.go
Labels: feature

#15 feature: resend otp
  go.mod
  module/auth/domain/request.go
  module/auth/handler/handler.go
  module/auth/interface.go
  module/auth/repository/repository.go
  module/auth/service/service.go
  routes/routes.go
Labels: feature

#16 improvment: feature/changepassword
  module/auth/handler/handler.go
  module/users/domain/request.go
  module/users/handler/handler.go
  module/users/interface.go
  module/users/repository/respository.go
  module/users/service/service.go
  routes/routes.go
Labels: improvment

#18 Bugfix/cicd
  .github/workflows/main.yml
  module/feature/auth/mocks/HandlerAuthInterface.go
  module/feature/auth/mocks/RepositoryAuthInterface.go
  module/feature/auth/mocks/ServiceAuthInterface.go
  module/feature/auth/service/service_test.go
Labels: bugfix

#19 feature: forgot password
  go.mod
  go.sum
  main.go
  module/feature/auth/dto/request.go
  module/feature/auth/dto/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/interface.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  routes/routes.go
Labels: feature

#20 improvement:email-template
  module/feature/auth/handler/handler.go
  module/feature/auth/service/service.go
  utils/email/email.go
  utils/email/template.html
Labels: improvment

#21 improvment: module category
  .github/workflows/main.yml
  config/config.go
  go.mod
  go.sum
  main.go
  module/entities/category_models.go
  module/feature/category/dto/request.go
  module/feature/category/dto/response.go
  module/feature/category/handler/handler.go
  module/feature/category/interface.go
  module/feature/category/repository/repository.go
  module/feature/category/service/service.go
  module/feature/product/dto/response.go
  routes/routes.go
  utils/upload/upload.go
Labels: improvment

#22 feature:golinter
  .github/workflows/golinter.yml
  config/config.go
  module/feature/auth/handler/handler.go
  module/feature/auth/mocks/HandlerAuthInterface.go
  module/feature/auth/mocks/RepositoryAuthInterface.go
  module/feature/auth/mocks/ServiceAuthInterface.go
  module/feature/auth/service/service_test.go
Labels: feature

#23 improvement: clean code category
  module/feature/category/handler/handler.go
  module/feature/category/service/service.go
Labels: improvment

#24 feature: get all pagination carousel
  main.go
  module/entities/carousel_models.go
  module/feature/carousel/dto/response.go
  module/feature/carousel/handler/handler.go
  module/feature/carousel/interface.go
  module/feature/carousel/repository/repository.go
  module/feature/carousel/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#25 feature:carousel
  module/feature/carousel/dto/request.go
  module/feature/carousel/handler/handler.go
  module/feature/carousel/interface.go
  module/feature/carousel/repository/repository.go
  module/feature/carousel/service/service.go
  routes/routes.go
Labels: feature

#26 improvement:voucher
  main.go
  module/entities/voucher_models.go
  module/feature/voucher/dto/request.go
  module/feature/voucher/dto/response.go
  module/feature/voucher/handler/handler.go
  module/feature/voucher/interface.go
  module/feature/voucher/repository/repository.go
  module/feature/voucher/service/service.go
  routes/routes.go
Labels: improvment

#27 feature:article
  main.go
  module/entities/article_models.go
  module/entities/users_models.go
  module/feature/article/dto/request.go
  module/feature/article/dto/response.go
  module/feature/article/handler/handler.go
  module/feature/article/interface.go
  module/feature/article/repository/repository.go
  module/feature/article/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#28 feature: user
  module/feature/auth/service/service.go
  module/feature/users/dto/request.go
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: feature

#29 feature:create-product
  go.mod
  main.go
  module/entities/category_models.go
  module/entities/product_models.go
  module/entities/users_models.go
  module/feature/product/dto/request.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  routes/routes.go
  utils/response/response.go
Labels: feature

#30 improvement : challenge
  main.go
  module/entities/challenge_models.go
  module/feature/challenge/dto/request.go
  module/feature/challenge/dto/response.go
  module/feature/challenge/handler/handler.go
  module/feature/challenge/interface.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  routes/routes.go
Labels: improvment

#31 feature: create address
  main.go
  module/feature/address/dto/request.go
  module/feature/address/dto/response.go
  module/feature/address/handler/handler.go
  module/feature/address/interface.go
  module/feature/address/repository/repository.go
  module/feature/address/service/service.go
  routes/routes.go
Labels: feature

#32 feature: create review
  main.go
  module/entities/reviews_models.go
  module/entities/users_models.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/dto/request.go
  module/feature/review/dto/response.go
  module/feature/review/handler/handler.go
  module/feature/review/interface.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
  module/feature/users/dto/response.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#33 feature:get product id and create product images
  module/entities/product_models.go
  module/feature/product/dto/request.go
  module/feature/product/dto/response.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  routes/routes.go
Labels: feature

#34 feature: create review photo
  main.go
  module/entities/product_models.go
  module/entities/reviews_models.go
  module/feature/product/dto/request.go
  module/feature/product/dto/response.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/dto/request.go
  module/feature/review/dto/response.go
  module/feature/review/handler/handler.go
  module/feature/review/interface.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
  routes/routes.go
Labels: feature

#35 feature: count average rating
  module/entities/reviews_models.go
  module/feature/product/dto/response.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/review/dto/response.go
  module/feature/review/handler/handler.go
  module/feature/review/interface.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
  routes/routes.go
Labels: feature

#37 improvement:create product
  module/feature/product/dto/request.go
  module/feature/product/service/service.go
Labels: improvment

#38 feature/update product
  module/feature/product/dto/request.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  routes/routes.go
Labels: feature, improvment

#41 feature: cart
  main.go
  module/entities/cart_models.go
  module/feature/cart/dto/request.go
  module/feature/cart/dto/response.go
  module/feature/cart/handler/handler.go
  module/feature/cart/interface.go
  module/feature/cart/repository/repository.go
  module/feature/cart/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#42 testing: carousel testing
  module/entities/article_models.go
  module/feature/carousel/dto/request.go
  module/feature/carousel/dto/response.go
  module/feature/carousel/handler/handler.go
  module/feature/carousel/interface.go
  module/feature/carousel/mocks/HandlerCarouselInterface.go
  module/feature/carousel/mocks/RepositoryCarouselInterface.go
  module/feature/carousel/mocks/ServiceCarouselInterface.go
  module/feature/carousel/repository/repository.go
  module/feature/carousel/service/service.go
  module/feature/carousel/service/service_test.go
  module/feature/category/handler/handler.go
  module/feature/category/interface.go
  module/feature/category/repository/repository.go
  module/feature/category/service/service.go
  routes/routes.go
Labels: improvment, testing

#44 feature: join-challenge
  module/entities/challenge_models.go
  module/feature/challenge/dto/request.go
  module/feature/challenge/dto/response.go
  module/feature/challenge/handler/handler.go
  module/feature/challenge/interface.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#45 improvement: join-challenge
  main.go
  module/feature/challenge/interface.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  module/feature/users/interface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: improvment

#46 Feature (article) : Get By Id, Manage Views, Filter By Date Range
  module/entities/category_models.go
  module/entities/product_models.go
  module/entities/reviews_models.go
  module/entities/users_models.go
  module/feature/article/dto/response.go
  module/feature/article/handler/handler.go
  module/feature/article/interface.go
  module/feature/article/repository/repository.go
  module/feature/article/service/service.go
  routes/routes.go
Labels: feature

#48 improvement:product and article
  module/entities/article_models.go
  module/entities/carousel_models.go
  module/entities/cart_models.go
  module/entities/category_models.go
  module/entities/challenge_models.go
  module/entities/product_models.go
  module/entities/reviews_models.go
  module/entities/users_models.go
  module/entities/voucher_models.go
  module/feature/article/service/service.go
  module/feature/product/dto/response.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
Labels: improvment

#49 feature:filtering product
  module/feature/product/dto/response.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
Labels: feature, improvment

#50 feature: users-total-challenge
  module/entities/users_models.go
  module/feature/challenge/dto/response.go
  module/feature/challenge/handler/handler.go
  module/feature/challenge/interface.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  module/feature/users/dto/response.go
  module/feature/users/interface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: feature

#51 feature:setup husky
  .husky/hooks/pre-commit
Labels: feature

#52 feature: order
  main.go
  module/entities/cart_models.go
  module/entities/order_models.go
  module/entities/voucher_models.go
  module/feature/cart/dto/response.go
  module/feature/cart/handler/handler.go
  module/feature/cart/interface.go
  module/feature/cart/repository/repository.go
  module/feature/cart/service/service.go
  module/feature/order/dto/request.go
  module/feature/order/dto/response.go
  module/feature/order/handler/handler.go
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/users/interface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  module/feature/voucher/dto/request.go
  module/feature/voucher/dto/response.go
  module/feature/voucher/handler/handler.go
  module/feature/voucher/interface.go
  module/feature/voucher/repository/repository.go
  module/feature/voucher/service/service.go
  routes/routes.go
  utils/database/migrate.go
  utils/generator.go
Labels: feature, improvment

#53 bugfix:order without voucher
  module/entities/order_models.go
  module/feature/order/dto/response.go
  module/feature/order/service/service.go
Labels: bugfix

#54 improvement: setup error handling
  module/feature/address/handler/handler.go
  module/feature/article/handler/handler.go
  module/feature/auth/handler/handler.go
  module/feature/auth/service/service.go
  module/feature/carousel/dto/request.go
  module/feature/carousel/handler/handler.go
  module/feature/cart/dto/response.go
  module/feature/cart/handler/handler.go
  module/feature/category/handler/handler.go
  module/feature/challenge/handler/handler.go
  module/feature/order/handler/handler.go
  module/feature/product/handler/handler.go
  module/feature/product/service/service.go
  module/feature/review/dto/response.go
  module/feature/review/handler/handler.go
  module/feature/users/handler/handler.go
  module/feature/users/service/service.go
  module/feature/voucher/handler/handler.go
  module/feature/voucher/repository/repository.go
  module/middlewares/auth.go
  routes/routes.go
  utils/response/response.go
Labels: improvment

#55 Feature/chatbot
  config/config.go
  go.mod
  go.sum
  main.go
  module/entities/chatbot_models.go
  module/feature/chatbot/dto/request.go
  module/feature/chatbot/handler/handler.go
  module/feature/chatbot/interface.go
  module/feature/chatbot/repository/repository.go
  module/feature/chatbot/service/service.go
  routes/routes.go
  utils/database/mongo.go
Labels: feature

#56 testing: challenge-testing
  module/feature/challenge/dto/response.go
  module/feature/challenge/handler/handler.go
  module/feature/challenge/interface.go
  module/feature/challenge/mocks/HandlerChallengeInterface.go
  module/feature/challenge/mocks/RepositoryChallengeInterface.go
  module/feature/challenge/mocks/ServiceChallengeInterface.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  module/feature/challenge/service/service_test.go
  module/feature/chatbot/service/service.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  routes/routes.go
  utils/database/mongo.go
Labels: testing

#57 bugfix: setup mongo
  .github/workflows/main.yml
  module/feature/product/dto/response.go
  module/feature/review/dto/request.go
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/repository/respository.go
  routes/routes.go
Labels: bugfix

#58 improvement: create address
  module/entities/users_models.go
  module/feature/address/dto/request.go
  module/feature/address/dto/response.go
  module/feature/address/handler/handler.go
  module/feature/address/service/service.go
  module/feature/order/dto/response.go
  module/feature/users/dto/response.go
  utils/database/mongo.go
Labels: improvment

#59 feature: order from cart
  module/feature/order/dto/request.go
  module/feature/order/handler/handler.go
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  routes/routes.go
Labels: feature

#60 feature: filter voucher
  module/feature/challenge/handler/handler.go
  module/feature/voucher/handler/handler.go
  module/feature/voucher/interface.go
  module/feature/voucher/repository/repository.go
  module/feature/voucher/service/service.go
Labels: feature

#61 feature: dashboard
  main.go
  module/feature/dashboard/dto/response.go
  module/feature/dashboard/handler/handler.go
  module/feature/dashboard/interface.go
  module/feature/dashboard/repository/repository.go
  module/feature/dashboard/service/service.go
  routes/routes.go
  utils/response/response.go
Labels: feature
