Repository capstone-kelompok-7/backend-disappear, pull requests merged in 2023-12, with the labels that each got.

#63 improvement: testing-challenge
  module/feature/challenge/handler/handler.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  module/feature/challenge/service/service_test.go
Labels: improvment, testing

#64 improvement: get product by id
  module/entities/reviews_models.go
  module/feature/product/dto/response.go
  module/feature/product/repository/repository.go
Labels: improvment

#65 feature: leaderboard
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: feature

#66 feature: get-display-vouchers
  module/feature/voucher/dto/response.go
  module/feature/voucher/handler/handler.go
  module/feature/voucher/interface.go
  module/feature/voucher/repository/repository.go
  module/feature/voucher/service/service.go
  routes/routes.go
Labels: feature

#67 feature: landing page
  module/feature/dashboard/dto/response.go
  module/feature/dashboard/handler/handler.go
  module/feature/dashboard/interface.go
  module/feature/dashboard/repository/repository.go
  module/feature/dashboard/service/service.go
  routes/routes.go
Labels: feature, improvment

#68 improvement : chatbot
  module/feature/chatbot/handler/handler.go
  module/feature/chatbot/interface.go
  module/feature/chatbot/service/service.go
  routes/routes.go
Labels: improvment

#69 feature: homepage
  main.go
  module/feature/homepage/dto/response.go
  module/feature/homepage/handler/handler.go
  module/feature/homepage/interface.go
  module/feature/homepage/repository/repository.go
  module/feature/homepage/service/service.go
  routes/routes.go
Labels: feature

#70 Improvement/filtering product
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  routes/routes.go
Labels: improvment

#73 feature: get activities customer
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: feature

#75 bugfix:fix bug response card dashboard
  module/feature/dashboard/handler/handler.go
  module/feature/dashboard/repository/repository.go
  module/feature/dashboard/service/service.go
Labels: bugfix

#76 feature/dashboard lasttransaction
  module/feature/dashboard/dto/response.go
  module/feature/dashboard/handler/handler.go
  module/feature/dashboard/interface.go
  module/feature/dashboard/repository/repository.go
  module/feature/dashboard/service/service.go
  routes/routes.go
Labels: feature, improvment

#77 bugfix:fix error pointer redis
  go.mod
  go.sum
  main.go
  module/feature/auth/service/service.go
  utils/caching/redis/redis.go
Labels: bugfix

#79 testing: address testing
  module/feature/address/mocks/HandlerAddressInterface.go
  module/feature/address/mocks/RepositoryAddressInterface.go
  module/feature/address/mocks/ServiceAddressInterface.go
  module/feature/address/service/service_test.go
Labels: testing

#80 feature: get user profile
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: feature

#84 improvement: filter product by promo
  module/feature/product/dto/response.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  utils/database/mongo.go
Labels: improvment

#85 bugfix: validation error while registering
  module/feature/auth/dto/request.go
  utils/validate.go
Labels: bugfix

#86 feature: get all order users
  module/feature/order/dto/response.go
  module/feature/order/handler/handler.go
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  routes/routes.go
Labels: feature

#87 feature: accept order
  module/feature/order/handler/handler.go
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  routes/routes.go
Labels: feature

#89 feature: article preferences
  module/entities/issues_models.go
  module/entities/users_models.go
  module/feature/article/dto/response.go
  module/feature/article/handler/handler.go
  module/feature/article/interface.go
  module/feature/article/repository/repository.go
  module/feature/article/service/service.go
  module/feature/users/dto/request.go
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
  utils/database/migrate.go
Labels: feature

#92 testing: homepage-testing
  module/feature/homepage/mocks/HandlerHomepageInterface.go
  module/feature/homepage/mocks/RepositoryHomepageInterface.go
  module/feature/homepage/mocks/ServiceHomepageInterface.go
  module/feature/homepage/service/service_test.go
Labels: testing

#94 feature: tracking order
  config/config.go
  module/entities/product_models.go
  module/feature/order/handler/handler.go
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/dto/response.go
  module/feature/product/repository/repository.go
  module/feature/review/dto/response.go
  module/feature/review/handler/handler.go
  module/feature/review/interface.go
  module/feature/review/repository/repository.go
  module/feature/review/service/service.go
  routes/routes.go
  utils/binderbyte/binderbyte.go
Labels: feature, improvment

#95 improvement: filter
  .github/workflows/main.yml
  module/entities/category_models.go
  module/feature/article/handler/handler.go
  module/feature/article/interface.go
  module/feature/article/repository/repository.go
  module/feature/article/service/service.go
  module/feature/order/dto/response.go
  module/feature/order/handler/handler.go
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: improvment

#96 feature: filter reviews
  module/feature/challenge/handler/handler.go
  module/feature/challenge/interface.go
  module/feature/challenge/mocks/RepositoryChallengeInterface.go
  module/feature/challenge/mocks/ServiceChallengeInterface.go
  module/feature/challenge/repository/repository.go
  module/feature/challenge/service/service.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
Labels: feature

#97 improvment: response homepage
  module/feature/homepage/dto/response.go
Labels: improvment

#98 feature: login social
  module/entities/users_models.go
  module/feature/auth/dto/request.go
  module/feature/auth/dto/response.go
  module/feature/auth/handler/handler.go
  module/feature/auth/interface.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  routes/routes.go
Labels: feature

#99 feature:getById Categories and Carousel
  module/feature/carousel/handler/handler.go
  module/feature/carousel/interface.go
  module/feature/category/handler/handler.go
  module/feature/category/interface.go
  routes/routes.go
Labels: feature

#100 feature: push notification fcm
  go.mod
  go.sum
  main.go
  module/entities/fcm_models.go
  module/feature/fcm/dto/request.go
  module/feature/fcm/dto/response.go
  module/feature/fcm/handler/handler.go
  module/feature/fcm/interface.go
  module/feature/fcm/repository/repository.go
  module/feature/fcm/service/service.go
  routes/routes.go
  utils/database/migrate.go
  utils/sendnotif/contoh-c4760-firebase-adminsdk-i3rk9-0a642f465e.json
  utils/sendnotif/sendnotif.go
Labels: feature

#101 improvement: chatbot
  module/entities/chatbot_models.go
  module/feature/cart/dto/response.go
  module/feature/cart/repository/repository.go
  module/feature/chatbot/dto/request.go
  module/feature/chatbot/handler/handler.go
  module/feature/chatbot/interface.go
  module/feature/chatbot/repository/repository.go
  module/feature/chatbot/service/service.go
  module/feature/fcm/dto/request.go
  routes/routes.go
Labels: improvment

#102 feature: order notification fcm
  .github/workflows/main.yml
  config/config.go
  main.go
  module/entities/fcm_models.go
  module/entities/users_models.go
  module/feature/fcm/handler/handler.go
  module/feature/fcm/interface.go
  module/feature/fcm/service/service.go
  module/feature/order/dto/request.go
  module/feature/order/service/service.go
  module/feature/product/handler/handler.go
  module/feature/users/dto/response.go
  routes/routes.go
  utils/sendnotif/contoh-c4760-firebase-adminsdk-i3rk9-0a642f465e.json
  utils/sendnotif/request.go
  utils/sendnotif/sendnotif.go
Labels: feature

#103 improvement: product recommendation with ai
  main.go
  module/entities/chatbot_models.go
  module/entities/users_models.go
  module/feature/article/handler/handler.go
  module/feature/article/interface.go
  module/feature/article/repository/repository.go
  module/feature/article/service/service.go
  module/feature/assistant/dto/request.go
  module/feature/assistant/handler/handler.go
  module/feature/assistant/interface.go
  module/feature/assistant/repository/repository.go
  module/feature/assistant/service/service.go
  module/feature/chatbot/repository/repository.go
  module/feature/chatbot/service/service.go
  module/feature/order/service/service.go
  module/feature/product/handler/handler.go
  module/feature/product/interface.go
  module/feature/product/repository/repository.go
  module/feature/product/service/service.go
  module/feature/users/dto/response.go
  module/feature/users/handler/handler.go
  module/feature/users/interface.go
  module/feature/users/mocks/HandlerUserInterface.go
  module/feature/users/mocks/RepositoryUserInterface.go
  module/feature/users/mocks/ServiceUserInterface.go
  module/feature/users/repository/respository.go
  module/feature/users/service/service.go
  routes/routes.go
Labels: improvment

#104 testing: cart testing
  module/entities/article_models.go
  module/feature/assistant/mocks/HandlerAssistantInterface.go
  module/feature/assistant/mocks/RepositoryAssistantInterface.go
  module/feature/assistant/mocks/ServiceAssistantInterface.go
  module/feature/assistant/service/service.go
  module/feature/cart/interface.go
  module/feature/cart/mocks/HandlerCartInterface.go
  module/feature/cart/mocks/RepositoryCartInterface.go
  module/feature/cart/mocks/ServiceCartInterface.go
  module/feature/cart/service/service.go
  module/feature/cart/service/service_test.go
  module/feature/product/mocks/HandlerProductInterface.go
  module/feature/product/mocks/RepositoryProductInterface.go
  module/feature/product/mocks/ServiceProductInterface.go
  module/feature/product/service/service.go
Labels: testing

#105 improvement: login with device token
  module/feature/auth/dto/request.go
  module/feature/auth/handler/handler.go
  module/feature/auth/interface.go
  module/feature/auth/repository/repository.go
  module/feature/auth/service/service.go
  utils/sendnotif/sendnotif.go
Labels: improvment

#106 testing:product testing
  module/feature/auth/service/service.go
  module/feature/product/service/service_test.go
Labels: testing

#107 testing : create order testing
  main.go
  module/entities/challenge_models.go
  module/feature/cart/service/service_test.go
  module/feature/challenge/service/service_test.go
  module/feature/fcm/handler/handler.go
  module/feature/fcm/interface.go
  module/feature/fcm/mocks/HandlerFcmInterface.go
  module/feature/fcm/mocks/RepositoryFcmInterface.go
  module/feature/fcm/mocks/ServiceFcmInterface.go
  module/feature/fcm/repository/repository.go
  module/feature/fcm/service/service.go
  module/feature/order/interface.go
  module/feature/order/mocks/HandlerOrderInterface.go
  module/feature/order/mocks/RepositoryOrderInterface.go
  module/feature/order/mocks/ServiceOrderInterface.go
  module/feature/order/service/service.go
  module/feature/order/service/service_test.go
  module/feature/voucher/mocks/HandlerVoucherInterface.go
  module/feature/voucher/mocks/RepositoryVoucherInterface.go
  module/feature/voucher/mocks/ServiceVoucherInterface.go
  utils/mocks/CacheRepository.go
  utils/mocks/FcmServiceInterface.go
  utils/mocks/GeneratorInterface.go
  utils/sendnotif/sendnotif.go
Labels: testing

#108 testing:fcm testing
  module/feature/fcm/mocks/HandlerFcmInterface.go
  module/feature/fcm/mocks/RepositoryFcmInterface.go
  module/feature/fcm/mocks/ServiceFcmInterface.go
  module/feature/fcm/service/service.go
  module/feature/fcm/service/service_test.go
Labels: testing

#110 testing: article testing
  module/entities/carousel_models.go
  module/entities/challenge_models.go
  module/entities/reviews_models.go
  module/entities/voucher_models.go
  module/feature/article/interface.go
  module/feature/article/mocks/HandlerArticleInterface.go
  module/feature/article/mocks/RepositoryArticleInterface.go
  module/feature/article/mocks/ServiceArticleInterface.go
  module/feature/article/service/service.go
  module/feature/article/service/service_test.go
  module/feature/auth/mocks/HandlerAuthInterface.go
  module/feature/auth/mocks/RepositoryAuthInterface.go
  module/feature/auth/mocks/ServiceAuthInterface.go
  module/feature/auth/service/service_test.go
Labels: testing

#111 review: testing-review
  module/feature/review/mocks/HandlerReviewInterface.go
  module/feature/review/mocks/RepositoryReviewInterface.go
  module/feature/review/mocks/ServiceReviewInterface.go
  module/feature/review/service/service_test.go
Labels: testing

#112 testing: improvement-testing-voucher
  module/feature/auth/service/service_test.go
  module/feature/order/service/service_test.go
  module/feature/voucher/service/service_test.go
Labels: testing

#113 testing: auth testing
  main.go
  module/feature/auth/handler/handler.go
  module/feature/auth/service/service.go
  module/feature/auth/service/service_test.go
  utils/email/email.go
  utils/mocks/EmailSenderInterface.go
Labels: testing

#114 testing: user testing
  module/feature/article/service/service_test.go
  module/feature/users/service/service.go
  module/feature/users/service/service_test.go
Labels: testing

#115 feature: email notification when ordering
  module/feature/order/interface.go
  module/feature/order/repository/repository.go
  module/feature/order/service/service.go
  utils/payment/request.go
Labels: feature
